
---
title: "Operating model comparison report"
subtitle: "ABT-MSE"
author: "Tom Carruthers"
date:  "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
geometry: margin=0.45in
fontsize: 10
---

### Operating model summary

```{r summary, results='asis',echo=FALSE}

Sres1<-Sres2<-NULL#array(NA,c(nOMs,8))
objtab<-array(NA,c(nOMs,15))
out<-M3read(OMdirs[1])
SSBstore<-array(0,c(nOMs,out$np,out$ny))
SSB0store<-array(0,c(nOMs,out$np))

OMlab<-unlist(lapply(strsplit(OMdirs,"/"),FUN=function(x)x[length(x)]))
CPUEres<-new('list')
OMnames<-rep("",nOMs)

for(i in 1:nOMs){

  out<-M3read(OMdirs[i])
  load(paste0(OMdirs[i],"/OMI"))
  OMnames[i]<-OMI@Name
  #"Model","Global","Catch","CPUE","Ind.","Length","SOO","PSAT","P Rec.","P mov","P sel","SRA pen","P SSB","P Fmod","P
  LHw<-c(1,OMI@LHw[c(1,2,3,4,5,6,8,9,10,11,12)],1,1)
  objtab[i,]<-c(OMI@Name,as.character(round(out$obj[c(14,1:13)]/LHw,1)))
  VBi<-out$VB/rep(apply(out$VB,4,mean),each=out$ny*out$ns*out$nr)
 
  for(k in 1:OMI@nCPUEq){

    tempdat<-subset(OMI@CPUEobs,OMI@CPUEobs[,4]==k)
    obs<-as.numeric(tempdat[,6])
     
    if(tempdat[1,7]==0){
       pred<-exp(out$lnqCPUE[k])*VBi[tempdat[,c(1,2,3,5)]]
  
    }else{
      pred<-apply(out$VL[,tempdat[1,2],tempdat[1,3],tempdat[1,4],],1,sum)
      pred<-exp(out$lnqCPUE[k])*pred/mean(pred)
      pred<-pred[tempdat[,1]]
    }
    
   # print(paste(i,k,is.na(sum(pred)),is.na(sum(obs))))
    
    if(i==1){
      CPUEres[[k]]<-log(obs)-log(pred)
    }else{
      CPUEres[[k]]<-cbind(CPUEres[[k]],log(obs)-log(pred))
    }

  }

  opt<-SRopt(out,plot=F,quiet=F,years=c(-Inf,Inf),type="BH",R0p=out$muR*exp(out$lnHR1))

  res<-MSY_FAST(FML=out$FL[out$ny,,,,], iALK=out$iALK[,out$ny,,], N=out$N[,out$ny,,,],
         wt_age=t(out$wt_age[out$ny,,]), M_age=out$M_age, mat_age=out$mat_age,
         R0s=out$muR, fixpars=opt$par1,SRtypes=rep("BH",2))

  res[,c(2,3,6,7,8)]<-round(res[,c(2,3,6,7,8)],3)
  res[,c(1,4,5)]<-round(res[,c(1,4,5)]/1000,0)
  SSBs<-round(out$SSB[,out$ny,out$ns]/1000,0)

  OFLs<-round(res$UMSY*(res$BMSY/res$SSBMSY)*SSBs,0)
  Deps<-round(out$SSB[,out$ny,out$spawns[1]]/out$SSB0,3)
  Sres1<-rbind(Sres1,c(OM=OMlab[i],res[1,],D=round(out$D[1],3),Dep=Deps[1],SSB=SSBs[1],OFL=OFLs[1]))
  Sres2<-rbind(Sres2,c(OM=OMlab[i],res[2,],D=round(out$D[2],3),Dep=Deps[2],SSB=SSBs[2],OFL=OFLs[2]))

  SSBstore[i,,]<-apply(out$SSB,1:2,mean)/1000
  SSB0store[i,]<-out$SSB0/1000

}

Sres1<-as.data.frame(Sres1)
Sres2<-as.data.frame(Sres2)

names(Sres1)[c(3,8,9)]<-names(Sres2)[c(3,8,9)]<-c("FMSYa","SSBrel","recMSY")
#write.csv(as.matrix(Sres1),file="C:/Users/tcar_/Documents/Sres1.csv")
objtab<-as.data.frame(objtab)
names(objtab)<-c("Model","Global","Catch","CPUE","Ind.","Length","SOO","PSAT","P Rec.","P mov","P sel","SRA pen","P SSB","P Fmod","P ratio")
	
kable(objtab[,c(1:9,13)],format='markdown')



```
``

### Residuals in indices

```{r residuals, fig.width=7.5, fig.height=9,echo=FALSE}
retseq<-function(res){

  nres<-length(res)
  str<-rep(1,nres)
  i<-1
  going<-TRUE
  while(going){

    same=TRUE
    j<-0
    while(same){

      if(res[i]!=res[i+j+1]|(j+i+1)==(nres+1)){

        same=FALSE
        str[i:(i+j)]<-j+1

      }else{
        j<-j+1
      }
    }

    if(i+j+1>nres)going=FALSE
    i<-i+j+1

  }

  str
}



resplot2<-function(yrs,res,horiz=T){
  
  resind<-length(res):1
  col<-rep('blue',length(res))
  col[res<0]<-'dark grey'
  ACcol<-c("white","white","#ff000010","#ff000030","#ff000080",rep('red',200))
  ACval<-retseq(res<0)
  bcol=ACcol[ACval]
  par(lwd = 2)
  barplot(res[resind],names.arg=yrs[resind],border='white',col="white",horiz=horiz)
  abline(v=c(-0.25,0.25),lty=2,col="grey",lwd=1)
  abline(v=c(-0.5,0.5),col="grey",lwd=1)
  barplot(res[resind],names.arg=yrs[resind],border=bcol[resind],col=col[resind],add=T,horiz=horiz)
  ac<-acf(res,plot=F)$acf[2,1,1]
  leg<-c(paste("StDev =",round(sd(res),2)),paste("AC =", round(ac,2)))
  legend('topleft',legend=leg,box.col="#ffffff99",bg="#ffffff99")
  #legend('topleft',legend=leg, box.col="#ffffff99",bg="#ffffff99")
  
}


chunk2 <- function(x,n) split(x, cut(seq_along(x), n, labels = FALSE))
groups<-chunk2(1:OMI@nCPUEq,4)

OMsel<-(1:nOMs)

for(j in 1:length(groups)){
  
  par(mfrow=c(length(groups[[j]]),length(OMsel)),mai=c(0.3,0.2,0.1,0.01),omi=c(0.3,0.3,0.2,0.05))
  
  for(k in groups[[j]]){
    
    for(i in OMsel){
      resplot2(yrs=rep(NA,length(CPUEres[[k]][,i])),res=CPUEres[[k]][,i])
      if(i==1)mtext(OMI@CPUEnames[k],2,line=1.5)
      if(k == groups[[j]][1])mtext(paste("OM =",i),3,line=0.8)
    }
    
  }
  
  cat("\n\n\\pagebreak\n")
  
}

mtext("Residual error. log(Obs.)-log(Pred.)",1,outer=T,line=0.5)



```


### Model estimates / reference points for Eastern stock

```{r refpoints_Et, results='asis',echo=FALSE,fig.width=5}


kable(Sres1)

```


### Model estimates / reference points for Western stock
```{r refpoints_W, results='asis',echo=FALSE,fig.width=5}

kable(Sres2)
  
```


### SSB trends

```{r SSBtrends, fig.width=7, fig.height=5.5,echo=FALSE}


par(mfrow=c(1,2),mai=c(0.5,0.5,0.5,0.2),omi=c(0,0.5,0,0.5))
pnams<-c("East stock","West stock")
cols<-c("black","#ff000090","#00ff0090","#0000ff90")

SSBEmax<-max(SSBstore[,1,])/1000
SSBWmax<-max(SSB0store[,2])/1000
SSBadj<-SSBEmax/SSBWmax


yrs<-OMI@years[1]:OMI@years[2]

for(pp in np:1){
 
  ylim<-c(0,max(SSBstore[,pp,])/1000)
  plot(yrs,SSBstore[1,pp,]/1000,col=cols[1],type="l",ylim=ylim,ylab="",xlab="")
 
  for(i in 2:nOMs){
   
    lines(yrs,SSBstore[i,pp,]/1000,col=cols[i])
  } 
 
  if(pp==2)legend('topleft',legend=OMnames,text.col=cols,text.font=2,bty='n')
  
  mtext(pnams[pp],3,line=0.6,cex=1.2,font=2)
}  

mtext("SSB (000,t)",2,outer=T,line=0.5,col="red",font=2)
mtext("SSB (000,t)",4,outer=T,line=0.5,col="blue",font=2)





```





